### ISSUE TITLE
懵了，还能压缩的越来越大嘛

### ISSUE THREAD

**Issue by yxy961112** [Dreamer365/topspeed-image-compressor#2]
![image](https://github.com/Dreamer365/topspeed-image-compressor/assets/49674927/f4c3b256-30e0-484f-9c9b-19e3c62d6cb4)

**Comment by Dreamer365** [comment]
有些图片确实存在压缩后体积反而增大的现象，能否提供一下原始图片呢？

**Comment by yxy961112** [comment]
![111111111111](https://github.com/Dreamer365/topspeed-image-compressor/assets/49674927/fb71bd77-2943-40e6-8a47-f76cb5c77f51)

**Comment by Dreamer365** [comment]
对提供的图片进行测试，确实出现了压缩后体积增大的现象，相关压缩算法后续会进行优化，请稍后关注新版本的发布。

**Comment by Dreamer365** [comment]
新版本已发布，可下载体验。

**Comment by 50431040** [comment]
还是越来越大..

**Comment by Dreamer365** [comment]
由于图片数据的多样性和不确定性均会对程序造成各种各样的影响，因此能否提供一下会导致上述问题的原始图片，便于快速排查出问题所在。
