### ISSUE TITLE
无法直接覆盖原图片

### ISSUE THREAD

**Issue by sujiahang** [Dreamer365/topspeed-image-compressor#3]
按照说明
选中：原始路径
如果前缀和后缀都不设置的话，压缩后的图片将直接覆盖原始图片。

但是无法直接覆盖，直接就失败

**Comment by Dreamer365** [comment]
感谢您的反馈！我在本地测试后的结果是可以覆盖原图。首先要确定您使用的是最新版本。如果您的压缩状态显示 “失败”，可以点击 “失败” 文本，将会弹出错误信息，请看一下弹出的错误信息是什么？或者方便的话可以提供一下相关图片，便于我在本地进行测试，谢谢！

**Comment by sujiahang** [comment]
设置项如下：
![image](https://github.com/Dreamer365/topspeed-image-compressor/assets/20947736/3f66c3c9-41db-4c8e-8312-ebf96914fee1)

报错信息：
![image](https://github.com/Dreamer365/topspeed-image-compressor/assets/20947736/55719219-85e8-40d4-ab1a-7e687e1c0908)

图片压缩包格式给你，我试过直接上传到github，再下载是可以成功的。
如果zip打不开，改成rar，github没办法上传rar的压缩包，我直接改后缀名了：
[0035.zip](https://github.com/Dreamer365/topspeed-image-compressor/files/12504082/0035.zip)

**Comment by Dreamer365** [comment]
经排查，某些图片是会存在上述问题，已将此标记为 Bug，后续版本将进行修复。

**Comment by sujiahang** [comment]
还有一个问题，我自定义路径的时候，如果是多文件夹压缩，多文件夹的里面的图片都只会保存到我自定义的根目录，如果有同名，后面的直接覆盖前面的。
难道不是应该根据我选的多个文件夹，在自定义根目录再创建相同的文件名，分别保存吗？

**Comment by Dreamer365** [comment]
目前的设计逻辑确实如此。无论是添加多个文件夹还是包含嵌套文件夹，都只是直接从中找出所有符合要求的图片，然后将这些图片统一添加到列表中，不会再记录各自所在的文件夹信息，当选择了 “自定义路径” 后，压缩后的图片将直接添加到对应的路径中，不会再按照原来各自所在的文件夹分区保存。

**Comment by sujiahang** [comment]
图片无法压缩的问题有出现在最新版本了，还是可以拿我上次上传的图片试
