### ISSUE TITLE
压缩改成单线程了？？

### ISSUE THREAD

**Issue by sujiahang** [Dreamer365/topspeed-image-compressor#8]
我从1.4直接升级到3.0，发现原来的10张图片，多线程一起压缩，现在改成一张单线程压缩了？
速度太慢了吧，下版本能改回多线程吗

**Comment by sujiahang** [comment]
或者有没有老哥有3.0以下的版本，压缩一次，我要花一天时间，这谁受得了。。。

**Comment by Dreamer365** [comment]
之前的机制（同时压缩多张图片）在压缩多张大体积图片时，会占用系统大量资源，而且图片体积越大，占用的资源就越多。之前已收到很多反馈，当设备的硬件性能不高时，如果图片的平均体积都达到上百MB，这种压缩方式经常会导致运行卡顿，因此在 3.0.0 版本中暂时调整到了每次只压缩一张。速度有可能会慢一些，但能最大限度保证其稳定运行。
不过，在新版本的开发规划中，已经准备加入一个配置选项，允许用户根据实际情况，自行选择 “同时压缩数量”，从而解决这个问题，还请关注后续版本的发布。

**Comment by Dreamer365** [comment]
最新版本 v3.0.1 已发布，增加了 “同时压缩数量” 配置项，可自由选择压缩数量。
